name: teleport
main: teleport.Main
version: 1.0
commands:
   newcuboid:
      description: L채gg till en ny skyddad ruta
      usage: /<command> [anv채ndare...]
   listcuboid:
      description: En lista p책 alla rutor som finns i v채rlden
      usage: /<command>
   remcuboid:
      description: Ta bort en ruta
      usage: /<command> <rutid>