name: teleport
main: teleport.Main
version: 1.0
commands:
   w:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   w-add:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   w-rem:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   w-list:
      description: Lista på platser
      usage: /<command>
