name: teleport
main: teleport.Main
version: 1.0
commands:
   w:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   wadd:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   wrem:
      description: Teleportera till en plats
      usage: /<command> [platsnamn]
   wlist:
      description: Lista på platser
      usage: /<command>
